# -*- coding: utf-8 -*-
"""AutoGluonStarter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ULOytrRHcw4GLl0qWgGnxUpr9zVQVYlr
"""

pip uninstall -y mkl

pip install --upgrade mxnet

pip install autogluon

pip install -U ipykernel

"""Restart Colab Runtime, then execute remaining cells"""

import autogluon as ag

from autogluon import TabularPrediction as task
train_data = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
test_data = task.Dataset(file_path='https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')
predictor = task.fit(train_data=train_data, label='class')
performance = predictor.evaluate(test_data)

