# -*- coding: utf-8 -*-
"""eli5_with_sklearn.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B44YHt77wfvfxJv2-wWnHCg0LdCsriPD

# Using eli_5 with sklearn

## Loading Data
"""

from sklearn.datasets import fetch_20newsgroups

categories = ['alt.atheism', 'soc.religion.christian', 
              'comp.graphics', 'sci.med']

twenty_train = fetch_20newsgroups(
    subset='train', categories = categories,
    shuffle=True,
    random_state=42
)

twenty_test = fetch_20newsgroups(
    subset='test', categories = categories,
    shuffle=True,
    random_state=42
)

"""## Make Pipeline"""

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegressionCV
from sklearn.pipeline import make_pipeline

vec = CountVectorizer()
clf = LogisticRegressionCV(verbose=True, n_jobs=-1, solver='lbfgs')
pipe = make_pipeline(vec, clf)

pipe.fit(twenty_train.data, twenty_train.target)

"""## Test predictions"""

from sklearn import metrics

def print_report(pipe):
    y_test = twenty_test.target
    y_pred = pipe.predict(twenty_test.data)
    report = metrics.classification_report(y_test, y_pred, target_names=twenty_test.target_names)
    print(report)
    print("Accuracy: - %0.2f" %(metrics.accuracy_score(y_test, y_pred)))

print_report(pipe)

"""# Checking what eli5 wants to say"""

! pip install eli5

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

import eli5

eli5.show_weights(clf, vec=vec, top=10, target_names=twenty_test.target_names)

eli5.show_prediction(clf, twenty_test.data[0], vec=vec, target_names=twenty_test.target_names)

"""# Trying with Tf-idf"""

from sklearn.feature_extraction.text import TfidfVectorizer

vec = TfidfVectorizer()
clf = LogisticRegressionCV()
pipe = make_pipeline(vec, clf)

pipe.fit(twenty_train.data, twenty_train.target)

print_report(pipe)

eli5.show_prediction(clf, twenty_test.data[0], vec=vec, target_names=twenty_test.target_names, targets=['sci.med'])